---
lr_schedulers:
  training_lr:
    class: MultiStepLR
    milestones: [45, 55, 65, 75, 80, 85, 87]
    gamma: 0.5

policies:
  - lr_scheduler:
      instance_name: training_lr
    starting_epoch: 0
    ending_epoch: 90
    frequency: 1
